# Generated by Django 2.2.5 on 2019-09-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskoapp', '0002_product_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='codigo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
